# Generated by Django 5.0.3 on 2024-03-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do País')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital')),
                ('subregion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Continente')),
                ('population', models.CharField(blank=True, max_length=100, null=True, verbose_name='População')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Região')),
            ],
        ),
    ]
